import Header from "@/components/Header";
import "./globals.css";
import Footer from "@/components/Footer";
import ClientLayout from "./(client)/layout";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
